# Generated by Django 2.2.6 on 2019-11-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('money', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
