# Generated by Django 2.2.6 on 2019-11-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_purchaserecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateNumber', models.CharField(max_length=8)),
                ('entrance', models.PositiveSmallIntegerField()),
                ('date', models.CharField(max_length=10)),
                ('arrivalTime', models.CharField(max_length=5)),
                ('staffName', models.CharField(max_length=10)),
                ('status', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
